### ISSUE TITLE
[BUG] General grammar revision 

### ISSUE THREAD

**Issue by stdevPavelmc** [stdevPavelmc/mailad#143]
**Describe the bug**
Do a general grammar & syntax revision, a job that @dienteperro started.

Please just before commit the change and fill a pull request mention this bug number to get it all under just one issue and fix all them with a simple merge after review.

Remember that in Github all pull request must be bind to a issue.

**Comment by stdevPavelmc** [comment]
Just mention this issue number on the description of the change, like this:

Related to #143, or fix #143, etc.

**Comment by stdevPavelmc** [comment]
@dienteperro Thanks for doing this, but please stop making a PR for every file.

In your local fork:
0. create a banch
1. Fix/Improve a file
2. Commit the change mentioning  "fix #143" on the commit line
3. iterate from 1 for each file that need fix/improvements
4. Al the end make a PR, just a PR with all the changes... in one PR...

Cheers.

**Comment by dienteperro** [comment]
ajjajaja, anotado, solo que no existe local fork.

**Comment by stdevPavelmc** [comment]
@dienteperro Si, en tu github tienes un fork... allí haz los cambios y luego hacern un PR con todos los cambios...
