### ISSUE TITLE
[BUG] ClamAV configured mirrors are not updated anymore

### ISSUE THREAD

**Issue by stdevPavelmc** [stdevPavelmc/mailad#147]
**Describe the bug**
If you live in Cuba and uses the listed alternate mirrors, well, they are not updated anymore, so you will get a non working AV filtering; the system will work, but AV filtering will be disabled until freshclam got updated, and as this will never happens....

**Expected behavior**
AV database working, av filtering activated

**Comment by stdevPavelmc** [comment]
Tentative **to test** mirrors:

- http://mirror.webtastix.net/clamav/
- https://packages.microsoft.com/clamav/
- http://52.230.121.169/clamav/
- http://40.65.182.21/clamav/
- http://40.114.136.21/clamav/
- http://13.90.56.68/clamav/
- http://13.79.133.120/clamav/
- http://13.75.64.135/clamav/
- http://137.135.134.16/clamav/
- http://40.85.80.91/clamav/
- Among others

**Comment by stdevPavelmc** [comment]
Todays Survey:

- http://mirror.webtastix.net/clamav/ [Broken]
- http://103.230.76.202/clamav/ [Broken]

**Comment by stdevPavelmc** [comment]
Todays Survey:

- http://mirrors.mediatemple.net/freshclam [Broken]
- http://repo.virtualhosting.hk/clamavdb/ [Broken]

**Comment by stdevPavelmc** [comment]
Found & tested some working but not differential download...  

- https://packages.microsoft.com/clamav/
- http://52.230.121.169/clamav/
- http://40.65.182.21/clamav/
- http://40.114.136.21/clamav/
- http://13.90.56.68/clamav/
- http://13.79.133.120/clamav/
- http://13.75.64.135/clamav/
- http://137.135.134.16/clamav/
- http://40.85.80.91/clamav/

At least one with a differential download would be nice (to help low bandwidth users) but practice likes to kill theory...

**Comment by stdevPavelmc** [comment]
I'm going to use this ones (random pick but the MS one)

- https://packages.microsoft.com/clamav/ [default]
- http://40.65.182.21/clamav/
- http://13.79.133.120/clamav/
- http://137.135.134.16/clamav/

**Comment by stdevPavelmc** [comment]
Fixed by #153

**Comment by PavelZabalotny** [comment]
Try to use this mirror:
https://www.syscu.net/download/clamav/
