### ISSUE TITLE
[FEAT] Independent Proxy settings for host/AV/Spamassassin etc

### ISSUE THREAD

**Issue by Joe1962** [stdevPavelmc/mailad#150]
**Problem description**
The proxy settings:
PROXY_HOST=""
PROXY_PORT=""
PROXY_USER=""
PROXY_PASS=""
are global. However,we often use local clamav update mirrors, which would then fail to update.

**Proposed solution**
Use independent proxy settings for AV, for example:
PROXY_AV_HOST=""
PROXY_AV_PORT=""
PROXY_AV_USER=""
PROXY_AV_PASS=""

**Comment by Joe1962** [comment]
> can be an additional `ENV_VAR` like `USE_PROXY_FOR_CLAMAV_UPDATE`

Probably more efficient that way.

**Comment by stdevPavelmc** [comment]
I was thinking about this, the flag/var is the most efficient way it seems.

I was thinking also on spamassasin but that is more in-frequent that the AV one... so not for not.

Just ClamAV...

**Comment by stdevPavelmc** [comment]
Something like this:

```
### ClamAV uses the declared proxy (see below) to update it's
# database?
#
# If you are in a proxied env and you have a local ClamAV mirror
# you will need to exclude ClamAV to use it, so this flag is for
# that.
#
# options: yes/no (default yes, case matters!)
AV_UPDATES_USE_PROXY=yes
```

**Comment by Joe1962** [comment]
> I was thinking also on spamassasin but that is more in-frequent that the AV one... so not for not.

I agree, never heard of anyone with a spamassasin mirror. Local clamav mirrors are very common here, though.
