### ISSUE TITLE
[BUG] ClamAV checks fails behind a proxy

### ISSUE THREAD

**Issue by Joe1962** [stdevPavelmc/mailad#151]
**Describe the bug**
When behind a corporate proxy, the command at line 150 in scripts/test_localhost.sh:

dig +short TXT current.cvd.clamav.net

will fail with an error and request to set ENABLE_AV=no. Also, it is fixed to current.cvd.clamav.net, when it should probably take into acount the value of USE_AV_ALTERNATE_MIRROR and AV_ALT_MIRRORS.

**To Reproduce**
1. Set PROXY variables.
2. Run make conf-check.
3. You will see an error message regarding DNS failure and be asked to set ENABLE_AV=no.
4. The script exits.

**Expected behavior**
Use another method to check this, or, on failure, ask if it should simply continue or not.

**Comment by stdevPavelmc** [comment]
Taking a peek on this issue, I have some concerns about it.

- ClamAV uses the txt DNS records to propagate updates, so you need a working DNS.
- Using freshclam you can "bruteforce" the updates and the DNS query must not be "needed" (not tested). I think even freshclam uses DNS to check if the mirror is up to date.
- I have nor tested it, can you test this and give us feedback?

If this is true just ignoring the DNS query when a AV_PROXY var is set will do the trick.

**Comment by stdevPavelmc** [comment]
Then, this is related with #150, related not dependent.

**Comment by stdevPavelmc** [comment]
#150 must be fixed first to take this to the workbench.

**Comment by Joe1962** [comment]
> * Using freshclam you can "bruteforce" the updates and the DNS query may not be "needed" (not tested). I think even freshclam uses DNS to check if the mirror is up to date.

When I manually configure freshclam to use our local mirror, it will update correctly, even though the only DNS record for the mirror is an A record.

**Comment by stdevPavelmc** [comment]
Issue re-opened, fix passed on my env, but has wrong presuptions... fixing that.
