### ISSUE TITLE
[FEAT] Multiple ADDC from config, improves redundancy

### ISSUE THREAD

**Issue by Joe1962** [stdevPavelmc/mailad#152]
**Feature**
Support multiple ADDC for HA.

**Solution**
Using something like this in /etc/mailad/mailad.conf:
HOSTAD=192.168.1.237 192.168.1.238 192.168.1.239

Should result in this in /etc/dovecot/dovecot-ldap.conf.ext:
uris = ldap://192.168.1.237:389/ ldap://192.168.1.238:389/ ldap://192.168.1.239:389/

And this in all 6 config files within /etc/postfix/ldap:
server_host = ldap://192.168.1.237:389 ldap://192.168.1.238:389 ldap://192.168.1.239:389

**Comment by stdevPavelmc** [comment]
Yep, confirmed

On http://www.postfix.org/ldap_table.5.html [postfix] and https://doc.dovecot.org/configuration_manual/authentication/ldap/ [dovecot] it's possible to specify multiple ADDC servers.

Working on this first.
