### ISSUE TITLE
[BUG] check for stalled mailboxes fails when using multiple DCs

### ISSUE THREAD

**Issue by stdevPavelmc** [stdevPavelmc/mailad#181]
**Describe the bug**
When you use multiples DCs for LDAP, the monthly check for stalled mailboxes fails as the functions to craft the LDAP URI with support for multiple DCs was not updated when this feature was introduced.

My mistake, sorry.

The solution is simple, will draft & test it tonight and commit with the fix ASAP.

**Self note:** bug is here: https://github.com/stdevPavelmc/mailad/blob/cbb029139d1458a2e83d56ef673a945f8a77eae6/scripts/check_maildirs.sh#L19-L26 the fix is to embed or link the get_ldap_uri function here: https://github.com/stdevPavelmc/mailad/blob/cbb029139d1458a2e83d56ef673a945f8a77eae6/common.conf#L320

**Comment by stdevPavelmc** [comment]
**WARNING!**

If you are using the multiple DCs option and have mailboxes with more than 1 year of age, please check your `/etc/mailad/mailad.conf` file and set the variable MAILDIRREMOVAL  to `no` as a safe measure, just in case.

**Comment by Joe1962** [comment]
Please remember to commit the fix to this issue... ;)
