### ISSUE TITLE
Descontinuado?

### ISSUE THREAD

**Issue by cz9dev** [stdevPavelmc/mailad#192]
Hola, esta proyecto se ha descontinuado?, no veo actualizaciones desde hace bastante. Seria una pena esta muy bien pensado.

**Comment by stdevPavelmc** [comment]
Saludos @cz9dev, nope, no está descontinuado.

Aparentemente no hay actividad porque ya el proyecto está maduro, salvo un bug encontrado hace poco que no es crítico, solo molesto (#191) que no he tenido de probar las soluciones que tengo propuestas.

Puede parecer que no hay actividad, pero eso se debe al diseño del soft, MailAD es un `conjunto de scripts` para deplegar un servidor de correos; por lo tanto los updates de los apps corren por el sistema operativo.

MailAD solo es la herramienta de configuración y salvo que alguien reporte un bug/fallo/vulnerabilidad o proponga un nuevo feature [si fuera con un PR much mejor] no hay nada que actualizar en realidad.

Las excepciones son los nuevos LTS de los SO soportados, generalmente cuando sale el nuevo LTS de ubuntu y el nuevo Debian, se actualizan los scripts una vez probados.

Te animo a que te unas al grupo de desarrollo y en cierta medida soporte en Telegram, por ahí se discute y se ayuda a los que están montando con dudas, etc.

Aquí tienes el link: https://t.me/MailAD_dev

**Comment by stdevPavelmc** [comment]
Además recientemente se lanzó MailD que es una versión para internet (no tiene algunas features de MailAD y es completamente sobre Docker) al estilo de IredMail; más pensado para dominios de internet sin tantas restricciones/tools como MailAD que está pensado para tener un control más granular de los users de un dominio, etc.

**Comment by stdevPavelmc** [comment]
Creo que es buen momento para recordarles a todos los que leen que esto es Software Libre, si alguien quiere participar como desarrollador ayudando a implementar nuevas features, ayudar a corregir errores o simplemente actualizar o traducir documentación, publicar un tutorial, etc...

Es más que bienvenido, simplemente únase al grupo de desarrollo en Telegram, discutamos las soluciones propuestas y adelante, todas las contribuciones son bienvenidas.

**Comment by stdevPavelmc** [comment]
Y terminamos este issue, cualqueir debate por el grupo de telegram.
