### ISSUE TITLE
I'm working on AD_Requirements

### ISSUE THREAD

**Issue by cz9dev** [stdevPavelmc/mailad#194]
No me deja subir los cambios a la rama develop

I'm working on AD_Requirements

_Originally posted by @cz9dev in https://github.com/stdevPavelmc/mailad/issues/10#issuecomment-2536568780_

**Comment by stdevPavelmc** [comment]
Es normal, revisa contributing.md.

Simplemente crea un fork de este repo en tu cuenta, crea una rama con el nombre del issue y descripción, por ejemplo:

194_translate_ad_reqs

Y cuando la tengas ok, haces un pull request to develop de mi repo ahí reviso y aprueba.

Es el flujo normal del gitflow...
