### ISSUE TITLE
Integracion a mailpiler

### ISSUE THREAD

**Issue by armandofcom** [stdevPavelmc/mailad#41]
Poder ponerle una direccion de que le mande una copia de todos los correos o a un buzon local o al buzon del mailpiler de los correos tanto entrada como saliente

**Comment by stdevPavelmc** [comment]
Hecho en el Commit d616f17 del PR #43  que está activo todavía, falta integración y configuración de SA/Clamav

Por lo que está pendiente... de cierrte

**Comment by stdevPavelmc** [comment]
Closed via PR #43
