### ISSUE TITLE
Reporte de los Correos del dia

### ISSUE THREAD

**Issue by armandofcom** [stdevPavelmc/mailad#42]
Seria bueno contar con un report, que se lo mande a una direccion o a una lista de informatico donde este un reporte con algunos datos como lo da zimbra:

Grand Totals
------------
messages

  3336   received
 15865   delivered
     0   forwarded
   388   deferred  (6839  deferrals)
    16   bounced
  3330   rejected (17%)
     0   reject warnings
     0   held
     0   discarded (0%)

264409k  bytes received
  1378m  bytes delivered
   804   senders
   238   sending hosts/domains
  1008   recipients
    86   recipient hosts/domains

Per-Hour Traffic Summary
------------------------
   time          received  delivered   deferred    bounced     rejected
   --------------------------------------------------------------------
   0000-0100          76        496        266          0         61 
   0100-0200         232       1071        259          0         87 
   0200-0300          51        238        285          0        175 
   0300-0400          29        121        266          0        112 
   0400-0500         209        927        270          0        136 
   0500-0600          53        214        268          0        138 
   0600-0700         108        440        292          0        168 
   0700-0800         247       1100        309          1        137 
   0800-0900         108        586        268          1        126 
   0900-1000         266       1249        303          0        193 
   1000-1100         114        518        297          0        166 
   1100-1200         125        945        330          3        140 
   1200-1300         106        507        292          1        150 
   1300-1400         278       1240        315          0        156 
   1400-1500         150        676        305          0        177 
   1500-1600         255       1143        294          2        168 
   1600-1700         198        844        304          3        151 
   1700-1800         105        804        289          2        160 
   1800-1900         101        427        288          1        161 
   1900-2000          83        354        296          0        111 
   2000-2100          70        308        307          0        110 
   2100-2200         247       1106        315          0        152 
   2200-2300         104        461        284          2        138 
   2300-2400          21         90        137          0         57 

Host/Domain Summary: Message Delivery (top 50)
----------------------------------------------
sent cnt  bytes   defers   avg dly max dly host/domain

Host/Domain Summary: Messages Received (top 50)
-----------------------------------------------
msg cnt   bytes   host/domain

top 50 Senders by message count
-------------------------------

top 50 Recipients by message count
----------------------------------

top 50 Senders by message size
------------------------------

top 50 Recipients by message size
---------------------------------

**Comment by Koratsuki** [comment]
Eso ya lo hace el pflogsumm.

**Comment by stdevPavelmc** [comment]
Hecho en este PR #37 
Closed in this PR #37 

We use pflogsumm to summarize the yersterday's emails
