### ISSUE TITLE
Footer or enterprise signature on every outgoing email

### ISSUE THREAD

**Issue by armandofcom** [stdevPavelmc/mailad#54]
Muchas empresas tienen un pie de firma a todos los correos que creo que esa opcion seria bueno poner

**Comment by stdevPavelmc** [comment]
Of curse, it will be optional, and disabled by default.

Altermime is the most used tool for that, it's on the TODO list.

**Comment by stdevPavelmc** [comment]
Work in progress on this feature

- Research on options (altermime has the focus by now)
- Test & implement
- Test extensively & improve

Then it will be ready...

**Comment by stdevPavelmc** [comment]
Sorry, closed by error, crappy mouse...

**Comment by stdevPavelmc** [comment]
closed by #78
