### ISSUE TITLE
Issues with PING Option to AD

### ISSUE THREAD

**Issue by danny920825** [stdevPavelmc/mailad#76]
Issues with PING Option to AD. On my LAN, the segmentation is classified by Security levels. And based on criteria, I have the AD in a VLAN alone with no one else. And the mail server in another VLAN. In the firewall there is a rule that allows mail to reach the AD through LDAP port 389, but the ICMP protocol is not allowed. Therefore, the AD check using PING does not work in cases like these. Not to mention that the ICMP in the servers is totally discouraged

**Comment by stdevPavelmc** [comment]
You are absolutely right.

I'm thinking on testing the connection with nc, as nc is on every distro... something like:

```
nc ad.domain.tld 389 -vz
```

And checking the return code... WiP

Thanks for your report!
