### ISSUE TITLE
[FEAT] Simplify the AD field handling 

### ISSUE THREAD

**Issue by stdevPavelmc** [stdevPavelmc/mailad#81]
Actually, to enable a user with his email we are setting 4 fields if the AD:

- Mail (Mail)
- Main Storage (Office)
- User Quota (Telephone number)
- Maildir (Webpage)

The initial reason behind this was the integration with Postfix and Courier/Dovecot, but as I have gained more insight of the integration and softwares, and also by users request to simplify that, and a possible standard ldap fields usage.

I will review that to try to simplify it.

- Use the UserPrincipalName as the mail atrribute, this approach has pros and cons...
- Use the sAMAccountName as maildir element: the challenge is to trick postfix and dovecot to add the final "/" to sign of a maildir.
- Remove the setting for the mail storage completely from the AD. Just hard coded in the settings while provisioning. (this may be the easiest to implement)
- Try to use the ldap quota attribute for the quota.
- Try to use a default hard coded quota (provision stage) and just override it if the specific user has a particular quota set 

Cheers.

**Comment by danny920825** [comment]
That is a very good idea. But it would be a better way to use each field for its function. In the case of mail, use the mail field itself, not userPrincipalName. As:
If you create another domain in the **DOMAIN.COM** forest as **SUB.DOMAIN.COM** the userPrincipalName would be user@sub.domain.com, for which a *UPN suffix* is created that globalizes it, but the email can be used to set the field of more direct and standardized way.

**Comment by stdevPavelmc** [comment]
> That is a very good idea. But it would be a better way to use each field for its function.

Aka: use standard AD LDAP fields: email, quota, home-directory... 

> In the case of mail, use the mail field itself, not userPrincipalName. As:
> If you create another domain in the **DOMAIN.COM** forest as **SUB.DOMAIN.COM** the userPrincipalName would be [user@sub.domain.com](mailto:user@sub.domain.com), for which a _UPN suffix_ is created that globalizes it, but the email can be used to set the field of more direct and standardized way.

That was the main reason I implemented it on the mail attribute and don't use the userPrincipalName one.

Thanks for your opinion.

**Comment by stdevPavelmc** [comment]
WiP, aka testing is under way for this...

We keep the use of the mail attribute for mail, @danny920825 has a valid point.

Test are focusing on this two items:

- Drop the mail storage declaration
- Use the sAMAccountName as the maildir var.

**Comment by stdevPavelmc** [comment]
> - Use the sAMAccountName as the maildir var.

Done in postfix, work in progress to archeive the same on dovecot

**Comment by stdevPavelmc** [comment]
> - Use the sAMAccountName as the maildir var.

`ldap(pavel@co7wt.cu,10.0.3.1,<Q/X5xM2x0pgKAAMB>): username changed pavel@co7wt.cu -> pavel`
`ldap(pavel,10.0.3.1,<Q/X5xM2x0pgKAAMB>): result: sAMAccountName=pavel`

Done with dovecot...

**Comment by stdevPavelmc** [comment]
Now we have the solution to **avoid**  to use:

- Web Page: for the personal maildir (will use sAMAccountName)
- Office: for the general mail storage.

But, we need to craft an script to migrate the users that are not using thisschema  (aka: old versions)

**Comment by stdevPavelmc** [comment]
The default Quota and then a specific one for some users is working no...

But, we may move the quota field from Telephone to Webpage... but that will need a migration script...

We are evaluating some alternatives

**Comment by stdevPavelmc** [comment]
Feature is complete, porting fixes to get it up to now.

**Comment by stdevPavelmc** [comment]
Closed by PR #130
